"""Competition application DTOs."""

from .competition_dto import (
    # Lifecycle Transitions
    ActivateCompetitionRequestDTO,
    ActivateCompetitionResponseDTO,
    # Golf Course Management
    AddGolfCourseBodyDTO,
    AddGolfCourseRequestDTO,
    AddGolfCourseResponseDTO,
    CancelCompetitionRequestDTO,
    CancelCompetitionResponseDTO,
    CloseEnrollmentsRequestDTO,
    CloseEnrollmentsResponseDTO,
    CompetitionGolfCourseResponseDTO,
    CompetitionResponseDTO,
    CompleteCompetitionRequestDTO,
    CompleteCompetitionResponseDTO,
    # Create & Update
    CreateCompetitionRequestDTO,
    CreateCompetitionResponseDTO,
    # Delete & Cancel
    DeleteCompetitionRequestDTO,
    DeleteCompetitionResponseDTO,
    GolfCourseDetailDTO,
    HoleResponseDTO,
    RemoveGolfCourseRequestDTO,
    RemoveGolfCourseResponseDTO,
    ReorderGolfCourseIdsRequest,
    ReorderGolfCoursesRequestDTO,
    ReorderGolfCoursesResponseDTO,
    StartCompetitionRequestDTO,
    StartCompetitionResponseDTO,
    TeeResponseDTO,
    UpdateCompetitionRequestDTO,
    UpdateCompetitionResponseDTO,
)
from .enrollment_dto import (
    # Cancel & Withdraw
    CancelEnrollmentRequestDTO,
    CancelEnrollmentResponseDTO,
    # Direct Enroll
    DirectEnrollPlayerRequestDTO,
    DirectEnrollPlayerResponseDTO,
    # Generic
    EnrollmentResponseDTO,
    # Handle Enrollment
    HandleEnrollmentRequestDTO,
    HandleEnrollmentResponseDTO,
    # Request Enrollment
    RequestEnrollmentRequestDTO,
    RequestEnrollmentResponseDTO,
    # Custom Handicap
    SetCustomHandicapRequestDTO,
    SetCustomHandicapResponseDTO,
    WithdrawEnrollmentRequestDTO,
    WithdrawEnrollmentResponseDTO,
)
from .round_match_dto import (
    # AssignTeams
    AssignTeamsBodyDTO,
    AssignTeamsRequestDTO,
    AssignTeamsResponseDTO,
    # ConfigureSchedule
    ConfigureScheduleBodyDTO,
    ConfigureScheduleRequestDTO,
    ConfigureScheduleResponseDTO,
    # CreateRound
    CreateRoundBodyDTO,
    CreateRoundRequestDTO,
    CreateRoundResponseDTO,
    # DeclareWalkover
    DeclareWalkoverBodyDTO,
    DeclareWalkoverRequestDTO,
    DeclareWalkoverResponseDTO,
    # DeleteRound
    DeleteRoundRequestDTO,
    DeleteRoundResponseDTO,
    # GenerateMatches
    GenerateMatchesBodyDTO,
    GenerateMatchesRequestDTO,
    GenerateMatchesResponseDTO,
    # GetMatchDetail
    GetMatchDetailRequestDTO,
    GetMatchDetailResponseDTO,
    # GetSchedule
    GetScheduleRequestDTO,
    GetScheduleResponseDTO,
    ManualPairingDTO,
    # Shared Response DTOs
    MatchPlayerResponseDTO,
    MatchResponseDTO,
    # ReassignMatchPlayers
    ReassignMatchPlayersBodyDTO,
    ReassignMatchPlayersRequestDTO,
    ReassignMatchPlayersResponseDTO,
    RoundResponseDTO,
    ScheduleDayDTO,
    TeamAssignmentResponseDTO,
    # UpdateMatchStatus
    UpdateMatchStatusBodyDTO,
    UpdateMatchStatusRequestDTO,
    UpdateMatchStatusResponseDTO,
    # UpdateRound
    UpdateRoundBodyDTO,
    UpdateRoundRequestDTO,
    UpdateRoundResponseDTO,
)

__all__ = [
    "ActivateCompetitionRequestDTO",
    "ActivateCompetitionResponseDTO",
    "AddGolfCourseBodyDTO",
    "AddGolfCourseRequestDTO",
    "AddGolfCourseResponseDTO",
    "AssignTeamsBodyDTO",
    "AssignTeamsRequestDTO",
    "AssignTeamsResponseDTO",
    "CancelCompetitionRequestDTO",
    "CancelCompetitionResponseDTO",
    "CancelEnrollmentRequestDTO",
    "CancelEnrollmentResponseDTO",
    "CloseEnrollmentsRequestDTO",
    "CloseEnrollmentsResponseDTO",
    "CompetitionGolfCourseResponseDTO",
    "CompetitionResponseDTO",
    "CompleteCompetitionRequestDTO",
    "CompleteCompetitionResponseDTO",
    "ConfigureScheduleBodyDTO",
    "ConfigureScheduleRequestDTO",
    "ConfigureScheduleResponseDTO",
    # Competition DTOs
    "CreateCompetitionRequestDTO",
    "CreateCompetitionResponseDTO",
    "CreateRoundBodyDTO",
    "CreateRoundRequestDTO",
    "CreateRoundResponseDTO",
    "DeclareWalkoverBodyDTO",
    "DeclareWalkoverRequestDTO",
    "DeclareWalkoverResponseDTO",
    "DeleteCompetitionRequestDTO",
    "DeleteCompetitionResponseDTO",
    "DeleteRoundRequestDTO",
    "DeleteRoundResponseDTO",
    "DirectEnrollPlayerRequestDTO",
    "DirectEnrollPlayerResponseDTO",
    "EnrollmentResponseDTO",
    "GenerateMatchesBodyDTO",
    "GenerateMatchesRequestDTO",
    "GenerateMatchesResponseDTO",
    "GetMatchDetailRequestDTO",
    "GetMatchDetailResponseDTO",
    "GetScheduleRequestDTO",
    "GetScheduleResponseDTO",
    "GolfCourseDetailDTO",
    "HandleEnrollmentRequestDTO",
    "HandleEnrollmentResponseDTO",
    "HoleResponseDTO",
    "ManualPairingDTO",
    "MatchPlayerResponseDTO",
    "MatchResponseDTO",
    "ReassignMatchPlayersBodyDTO",
    "ReassignMatchPlayersRequestDTO",
    "ReassignMatchPlayersResponseDTO",
    "RemoveGolfCourseRequestDTO",
    "RemoveGolfCourseResponseDTO",
    "ReorderGolfCourseIdsRequest",
    "ReorderGolfCoursesRequestDTO",
    "ReorderGolfCoursesResponseDTO",
    # Enrollment DTOs
    "RequestEnrollmentRequestDTO",
    "RequestEnrollmentResponseDTO",
    "RoundResponseDTO",
    "ScheduleDayDTO",
    "SetCustomHandicapRequestDTO",
    "SetCustomHandicapResponseDTO",
    "StartCompetitionRequestDTO",
    "StartCompetitionResponseDTO",
    "TeamAssignmentResponseDTO",
    "TeeResponseDTO",
    "UpdateCompetitionRequestDTO",
    "UpdateCompetitionResponseDTO",
    "UpdateMatchStatusBodyDTO",
    "UpdateMatchStatusRequestDTO",
    "UpdateMatchStatusResponseDTO",
    "UpdateRoundBodyDTO",
    "UpdateRoundRequestDTO",
    "UpdateRoundResponseDTO",
    "WithdrawEnrollmentRequestDTO",
    "WithdrawEnrollmentResponseDTO",
]
