"""add golf course update fields

Revision ID: bad5e4052f9f
Revises: af107e8f82c6
Create Date: 2026-01-30 23:07:56.054535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad5e4052f9f'
down_revision: Union[str, None] = 'af107e8f82c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add original_golf_course_id column (nullable, FK to golf_courses.id)
    op.add_column(
        'golf_courses',
        sa.Column(
            'original_golf_course_id',
            sa.UUID(),
            nullable=True,
            comment='If not NULL, this is a clone/update proposal of the original golf course'
        )
    )

    # Add is_pending_update column (boolean, default FALSE)
    op.add_column(
        'golf_courses',
        sa.Column(
            'is_pending_update',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('FALSE'),
            comment='TRUE if this golf course has a pending update clone'
        )
    )

    # Add foreign key constraint
    op.create_foreign_key(
        'fk_golf_courses_original_golf_course_id',
        'golf_courses',
        'golf_courses',
        ['original_golf_course_id'],
        ['id'],
        ondelete='CASCADE'
    )

    # Add index for original_golf_course_id (for faster queries of clones)
    op.create_index(
        'ix_golf_courses_original_golf_course_id',
        'golf_courses',
        ['original_golf_course_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_golf_courses_original_golf_course_id', table_name='golf_courses')
    op.drop_constraint('fk_golf_courses_original_golf_course_id', 'golf_courses', type_='foreignkey')
    op.drop_column('golf_courses', 'is_pending_update')
    op.drop_column('golf_courses', 'original_golf_course_id')
    # ### end Alembic commands ###
